# Generated by Django 3.1.5 on 2021-01-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pokemon Types',
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('next_evolution', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pokedex.pokemonspecies')),
                ('pokemon_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pokedex.pokemontypes', verbose_name='Type(s)')),
            ],
            options={
                'verbose_name_plural': 'Pokemon Species',
            },
        ),
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pokemonspecies', verbose_name='Pokemon Species')),
            ],
            options={
                'verbose_name_plural': 'Pokemons',
            },
        ),
    ]
