# Generated by Django 3.1.5 on 2021-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='evolution_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
