# Generated by Django 3.1.5 on 2021-01-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemonspecies_evolution_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pokemonspecies'),
        ),
    ]
