# Generated by Django 3.1.5 on 2021-01-23 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20210123_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolution_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Please enter up to 100. Leave blank not applicable.'), django.core.validators.MaxValueValidator(100, message='Please enter up to 100. Leave blank not applicable.')]),
        ),
    ]
