# Generated by Django 3.1.5 on 2021-01-23 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemonspecies_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='level',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, message='Please enter up to 100. Leave blank if not applicable.'), django.core.validators.MaxValueValidator(100, message='Please enter up to 100. Leave blank if not applicable.')]),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='trainer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
