# Generated by Django 3.1.5 on 2021-01-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_pokemons_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='pokemon_type',
        ),
    ]
