# Generated by Django 3.1.5 on 2021-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_remove_pokemons_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonspecies',
            name='pokemon_type',
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='pokemon_type',
            field=models.ManyToManyField(to='pokedex.PokemonTypes'),
        ),
    ]
