# Generated by Django 3.1.5 on 2021-01-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_auto_20210124_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='pokemon_type',
            field=models.ManyToManyField(related_name='poke_types', to='pokedex.PokemonTypes'),
        ),
    ]
