# Generated by Django 3.1.5 on 2021-01-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_auto_20210124_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonspecies',
            name='pokemon_type',
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='poke_type',
            field=models.ManyToManyField(to='pokedex.PokemonTypes', verbose_name='Pokemon Type(s)'),
        ),
    ]
